FROM gradle:jdk11 as builder

COPY --chown=gradle:gradle . /home/gradle/src/app
WORKDIR /home/gradle/src/app
RUN gradle clean build

FROM openjdk:11

ENV APP_HOME=/usr/local/app/
WORKDIR $APP_HOME

COPY --from=builder /home/gradle/src/app/build/libs/configuration-service-*.jar ./app.jar

EXPOSE 8888

CMD ["java","-jar","-Dspring.profiles.active=docker","app.jar"]
