FROM gradle:jdk8 as builder

COPY --chown=gradle:gradle . /home/gradle/src/app
WORKDIR /home/gradle/src/app
RUN gradle clean build

FROM openjdk:8

ENV APP_HOME=/usr/local/app/
WORKDIR $APP_HOME

COPY --from=builder /home/gradle/src/app/build/libs/zuul-service-*.jar ./app.jar

EXPOSE 8888
EXPOSE 8761
EXPOSE 8090

CMD ["java","-jar","-Dspring.profiles.active=docker","app.jar"]
