FROM openjdk:8
ENV APP_HOME=/usr/local/app/
WORKDIR $APP_HOME
COPY ./build/libs/zuul-service-*.jar ./app.jar
EXPOSE 8888
EXPOSE 8761
EXPOSE 8090
CMD ["java","-jar","-Dspring.profiles.active=docker-all","app.jar"]
