zuul:
  prefix: /api
  routes:
    gateway:
      sensitiveHeaders:
      path: /gateway/**
      serviceId: GATEWAY-SERVICE
    event:
      path: /event/**
      serviceId: EVENT-SERVICE
    user:
      path: /user/**
      serviceId: USER-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: eureka-service

server:
  port: 8090

spring:
  application:
    name: zuul-service
