zuul:
  prefix: /api
  routes:
    gateway:
      sensitiveHeaders:
      path: /gateway/**
      serviceId: GATEWAY-SERVICE
      url: http://gateway-service:9999
    event:
      path: /event/**
      serviceId: EVENT-SERVICE
      url: http://event-service:8000
    user:
      path: /user/**
      serviceId: USER-SERVICE
      url: http://user-service:8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: eureka-service

server:
  port: 8090

spring:
  application:
    name: zuul-service
